name: Release pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'feat/**'
      - 'hotfix/**'
      - 'ACT-**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    name: Unit Test + Linting + Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install deps
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Run storybook build
        run: npm run build-storybook

  visual-test:
    name: Visual testing with baseline comparison
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
          start: npm start
          project: ./test/functional
      - name: upload diffs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-diffs-screenshots
          path: test/functional/cypress-image-diff-screenshots

  build-and-deploy:
    name: Build, Deploy to GitHub pages, Release npm package
    needs: [test, visual-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Trigger release process only on main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: 🛠 Install & Build
        run: |
          npm ci
          npm run build-storybook
          npm run build-package
      - name: 🚀 Release npm package
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/git
          branches: |
            [
              'main'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: 📃 Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: github-pages
          folder: storybook-static
          target-folder: docs
